// Rebuilds the EVTX parser (Rust `evtx` crate -> WASM) and regenerates src/evtx/*.generated.*.
// Requires: rustup target add wasm32-unknown-unknown ; cargo install wasm-bindgen-cli --version 0.2.100 --locked
// The outputs are committed so contributors without a Rust toolchain can still build the app.
import { execFileSync } from 'node:child_process'
import fs from 'node:fs'
import crypto from 'node:crypto'
import path from 'node:path'

const root = path.resolve(import.meta.dirname, '..')
const crate = path.join(root, 'evtx-wasm')
const out = path.join(root, 'src/evtx')
const run = (cmd, args, cwd) => execFileSync(cmd, args, { cwd, stdio: 'inherit' })

run('cargo', ['build', '--release', '--locked', '--target', 'wasm32-unknown-unknown'], crate)
const wasmIn = path.join(crate, 'target/wasm32-unknown-unknown/release/evtx_wasm.wasm')
const tmp = path.join(crate, 'target/bindgen')
fs.rmSync(tmp, { recursive: true, force: true })
run('wasm-bindgen', ['--target', 'web', '--no-typescript', '--out-dir', tmp, wasmIn], crate)

let glue = fs.readFileSync(path.join(tmp, 'evtx_wasm.js'), 'utf8')
// The default loader does fetch(new URL('..wasm', import.meta.url)). That would be blocked by connect-src 'none' and makes
// the bundler emit the wasm as a separate asset. We only ever call initSync() with bytes, so drop the fetching path.
glue = glue.replace(/async function __wbg_init[\s\S]*?\n}\n/, 'async function __wbg_init() { throw new Error("fetch-based init is disabled; use initSync") }\n')
if (/import\.meta\.url/.test(glue)) throw new Error('glue still references import.meta.url; update the patch in build-evtx.mjs')
fs.writeFileSync(path.join(out, 'evtx_wasm.generated.js'), '// GENERATED by scripts/build-evtx.mjs. Do not edit.\n// @ts-nocheck\n' + glue)

const wasm = fs.readFileSync(path.join(tmp, 'evtx_wasm_bg.wasm'))
const sha = crypto.createHash('sha256').update(wasm).digest('hex')
fs.writeFileSync(path.join(out, 'wasmBytes.generated.ts'),
  `// GENERATED by scripts/build-evtx.mjs. Do not edit.\n// sha256(wasm) = ${sha}\nexport const WASM_SHA256 = '${sha}'\nexport const WASM_BASE64 = '${wasm.toString('base64')}'\n`)
console.log(`evtx wasm: ${wasm.length} bytes, sha256 ${sha}`)
